package main

import "fmt"

func main() {
	nextFib := 0
	fibSum := 0
	// Create a slice of ints to start the Fibonacci sequence
	fibs := []int{1, 2} // Put the first 2 elements in
	for {
		nextFib = fibs[len(fibs)-1] + fibs[len(fibs)-2]
		if nextFib <= 4000000 {
			fibs = append(fibs, nextFib)
		} else {
			break
		}
	}

	// Now, we iterate over []fibs, check for even numbers and sum them.
	for _, fib := range fibs {
		if fib % 2 == 0 {
			fmt.Println(fib)
			fibSum += fib
		}
	}
	fmt.Println("The sum of all of the even Fibonacci numbers less than 4,000,000 is: ", fibSum)
}

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
// first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.